version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "monthly"
